# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wh_habitica', '0001_squashed_0002_auto_20151226_1552'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='habitica',
            table='habitica_habitica',
        ),
    ]
