# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wunderlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wunderlist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wunderlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
