# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wunderlist', '0003_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(max_length=255, verbose_name='Token'),
        ),
    ]
