# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wunderlist', '0007_connection_tasks_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='tasks_completed',
            field=models.IntegerField(default=0, verbose_name='Tasks completed'),
        ),
    ]
