# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wunderlist', '0008_auto_20151226_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='webhook_id',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Webhook ID'),
            preserve_default=False,
        ),
    ]
