# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wunderlist', '0010_auto_20151226_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_upscored',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Up-Scored'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
