# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wunderlist', '0012_auto_20151230_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='habit',
            new_name='habit_id',
        ),
    ]
